# Generated by Django 4.0.1 on 2022-02-04 18:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoadImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_image', models.CharField(max_length=50)),
                ('url_image', models.CharField(max_length=50)),
                ('format_img', models.CharField(max_length=25)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('edited', models.DateTimeField(blank=True, default=None, null=True)),
                ('image', models.ImageField(upload_to='img')),
            ],
            options={
                'db_table': 'loadImage',
            },
        ),
    ]
