# Generated by Django 4.0.1 on 2022-02-04 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loadImage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loadimagemodel',
            name='image',
        ),
    ]
