# Generated by Django 4.0.1 on 2022-02-04 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadImage', '0002_remove_loadimagemodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadimagemodel',
            name='name_image',
            field=models.ImageField(upload_to='img'),
        ),
    ]
