# Generated by Django 4.0.1 on 2022-02-06 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loadImage', '0005_alter_loadimagemodel_name_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadimagemodel',
            name='format_img',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='loadimagemodel',
            name='name_image',
            field=models.ImageField(blank='', default='', upload_to='img'),
        ),
        migrations.AlterField(
            model_name='loadimagemodel',
            name='url_image',
            field=models.CharField(max_length=100),
        ),
    ]
