# Generated by Django 4.0.1 on 2022-02-06 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loadImage', '0006_alter_loadimagemodel_format_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loadimagemodel',
            old_name='name_image',
            new_name='name_img',
        ),
        migrations.RenameField(
            model_name='loadimagemodel',
            old_name='url_image',
            new_name='url_img',
        ),
    ]
